### ISSUE TITLE
Numbers issue

### ISSUE THREAD

**Issue by sadkim** [3aransia/3aransia#46]
1 -  I don't know if all of you use 4 as غ , Some moroccans use it 
2 - when we write a sentence with a number the translator stops . except for 'chrit 9 dlbidat' (xD) or '7 dlbidat', it's translated as 'شريت ق دلبيدات' 
So if 9 or 4 or 7 are used in a word (not an integer) they should interpreted as numbers

**Comment by aminblm** [comment]
- 1 at one can be added of course. It also depends on the regions of the Moroccan country very much. Since 4 is not occupied we can think of adding it. For the time being it is more the R but it need more accuracy to translate R for the moment because of the 'less' intelligent application that doesn't know when it is the right R.

- 2 this is a really good issue. It was in my to-do list but forgot to write it on the issues. This is definitely a good first issue and thank you very much for pointing it out.

* You can also add a new issue about the bowls in the beginning of the word.

**Comment by aminblm** [comment]
Fixe with last merge with master
